// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: authen/v1/admin.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssueRegTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxUses       int32                  `protobuf:"varint,1,opt,name=max_uses,json=maxUses,proto3" json:"max_uses,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Scopes        []string               `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	Label         string                 `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	AutoApprove   bool                   `protobuf:"varint,6,opt,name=auto_approve,json=autoApprove,proto3" json:"auto_approve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueRegTokenRequest) Reset() {
	*x = IssueRegTokenRequest{}
	mi := &file_authen_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueRegTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueRegTokenRequest) ProtoMessage() {}

func (x *IssueRegTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueRegTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueRegTokenRequest) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *IssueRegTokenRequest) GetMaxUses() int32 {
	if x != nil {
		return x.MaxUses
	}
	return 0
}

func (x *IssueRegTokenRequest) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *IssueRegTokenRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *IssueRegTokenRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *IssueRegTokenRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *IssueRegTokenRequest) GetAutoApprove() bool {
	if x != nil {
		return x.AutoApprove
	}
	return false
}

type RegToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RemainingUses int32                  `protobuf:"varint,2,opt,name=remaining_uses,json=remainingUses,proto3" json:"remaining_uses,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Scopes        []string               `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	Roles         []string               `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	Label         string                 `protobuf:"bytes,6,opt,name=label,proto3" json:"label,omitempty"`
	Id            string                 `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	Revoked       bool                   `protobuf:"varint,8,opt,name=revoked,proto3" json:"revoked,omitempty"`
	AutoApprove   bool                   `protobuf:"varint,9,opt,name=auto_approve,json=autoApprove,proto3" json:"auto_approve,omitempty"`
	MaxUses       int32                  `protobuf:"varint,10,opt,name=max_uses,json=maxUses,proto3" json:"max_uses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegToken) Reset() {
	*x = RegToken{}
	mi := &file_authen_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegToken) ProtoMessage() {}

func (x *RegToken) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegToken.ProtoReflect.Descriptor instead.
func (*RegToken) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *RegToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegToken) GetRemainingUses() int32 {
	if x != nil {
		return x.RemainingUses
	}
	return 0
}

func (x *RegToken) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *RegToken) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *RegToken) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *RegToken) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *RegToken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegToken) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *RegToken) GetAutoApprove() bool {
	if x != nil {
		return x.AutoApprove
	}
	return false
}

func (x *RegToken) GetMaxUses() int32 {
	if x != nil {
		return x.MaxUses
	}
	return 0
}

type ListRegTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRegTokensRequest) Reset() {
	*x = ListRegTokensRequest{}
	mi := &file_authen_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRegTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRegTokensRequest) ProtoMessage() {}

func (x *ListRegTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRegTokensRequest.ProtoReflect.Descriptor instead.
func (*ListRegTokensRequest) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ListRegTokensRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type RegTokenList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*RegToken            `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegTokenList) Reset() {
	*x = RegTokenList{}
	mi := &file_authen_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegTokenList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegTokenList) ProtoMessage() {}

func (x *RegTokenList) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegTokenList.ProtoReflect.Descriptor instead.
func (*RegTokenList) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *RegTokenList) GetTokens() []*RegToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *RegTokenList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RevokeRegTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRegTokenRequest) Reset() {
	*x = RevokeRegTokenRequest{}
	mi := &file_authen_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRegTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRegTokenRequest) ProtoMessage() {}

func (x *RevokeRegTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRegTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeRegTokenRequest) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeRegTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RevokeRegTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRegTokenResponse) Reset() {
	*x = RevokeRegTokenResponse{}
	mi := &file_authen_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRegTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRegTokenResponse) ProtoMessage() {}

func (x *RevokeRegTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRegTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeRegTokenResponse) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{5}
}

type PublicKeyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	KeyType       string                 `protobuf:"bytes,2,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	IdentityId    string                 `protobuf:"bytes,3,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	Label         string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	RegisteredAt  int64                  `protobuf:"varint,5,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKeyInfo) Reset() {
	*x = PublicKeyInfo{}
	mi := &file_authen_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeyInfo) ProtoMessage() {}

func (x *PublicKeyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeyInfo.ProtoReflect.Descriptor instead.
func (*PublicKeyInfo) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *PublicKeyInfo) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *PublicKeyInfo) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *PublicKeyInfo) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *PublicKeyInfo) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *PublicKeyInfo) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

func (x *PublicKeyInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PublicKeyInfo) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type ListKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	IdentityId    string                 `protobuf:"bytes,2,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeysRequest) Reset() {
	*x = ListKeysRequest{}
	mi := &file_authen_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeysRequest) ProtoMessage() {}

func (x *ListKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeysRequest.ProtoReflect.Descriptor instead.
func (*ListKeysRequest) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *ListKeysRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListKeysRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *ListKeysRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type KeyList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*PublicKeyInfo       `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyList) Reset() {
	*x = KeyList{}
	mi := &file_authen_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyList) ProtoMessage() {}

func (x *KeyList) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyList.ProtoReflect.Descriptor instead.
func (*KeyList) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *KeyList) GetKeys() []*PublicKeyInfo {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *KeyList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyRequest) Reset() {
	*x = DeleteKeyRequest{}
	mi := &file_authen_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyRequest) ProtoMessage() {}

func (x *DeleteKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeyRequest) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type DeleteKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyResponse) Reset() {
	*x = DeleteKeyResponse{}
	mi := &file_authen_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyResponse) ProtoMessage() {}

func (x *DeleteKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeyResponse) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{10}
}

type PolicyRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Condition     string                 `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyRule) Reset() {
	*x = PolicyRule{}
	mi := &file_authen_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRule) ProtoMessage() {}

func (x *PolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRule.ProtoReflect.Descriptor instead.
func (*PolicyRule) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *PolicyRule) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PolicyRule) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PolicyRule) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *PolicyRule) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

type ApplyPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Rules         []*PolicyRule          `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyPolicyRequest) Reset() {
	*x = ApplyPolicyRequest{}
	mi := &file_authen_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPolicyRequest) ProtoMessage() {}

func (x *ApplyPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPolicyRequest.ProtoReflect.Descriptor instead.
func (*ApplyPolicyRequest) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *ApplyPolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplyPolicyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ApplyPolicyRequest) GetRules() []*PolicyRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type ApplyPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyId      string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyPolicyResponse) Reset() {
	*x = ApplyPolicyResponse{}
	mi := &file_authen_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPolicyResponse) ProtoMessage() {}

func (x *ApplyPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPolicyResponse.ProtoReflect.Descriptor instead.
func (*ApplyPolicyResponse) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *ApplyPolicyResponse) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

type ListPoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesRequest) Reset() {
	*x = ListPoliciesRequest{}
	mi := &file_authen_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesRequest) ProtoMessage() {}

func (x *ListPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ListPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *ListPoliciesRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type PolicyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Rules         []*PolicyRule          `protobuf:"bytes,4,rep,name=rules,proto3" json:"rules,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyInfo) Reset() {
	*x = PolicyInfo{}
	mi := &file_authen_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyInfo) ProtoMessage() {}

func (x *PolicyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyInfo.ProtoReflect.Descriptor instead.
func (*PolicyInfo) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *PolicyInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PolicyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PolicyInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PolicyInfo) GetRules() []*PolicyRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *PolicyInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PolicyInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type PolicyList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*PolicyInfo          `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyList) Reset() {
	*x = PolicyList{}
	mi := &file_authen_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyList) ProtoMessage() {}

func (x *PolicyList) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyList.ProtoReflect.Descriptor instead.
func (*PolicyList) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *PolicyList) GetPolicies() []*PolicyInfo {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *PolicyList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CheckPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityId    string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Context       map[string]string      `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPolicyRequest) Reset() {
	*x = CheckPolicyRequest{}
	mi := &file_authen_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPolicyRequest) ProtoMessage() {}

func (x *CheckPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPolicyRequest.ProtoReflect.Descriptor instead.
func (*CheckPolicyRequest) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *CheckPolicyRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *CheckPolicyRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckPolicyRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CheckPolicyRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type CheckPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	MatchedRules  []string               `protobuf:"bytes,2,rep,name=matched_rules,json=matchedRules,proto3" json:"matched_rules,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPolicyResponse) Reset() {
	*x = CheckPolicyResponse{}
	mi := &file_authen_v1_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPolicyResponse) ProtoMessage() {}

func (x *CheckPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPolicyResponse.ProtoReflect.Descriptor instead.
func (*CheckPolicyResponse) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{18}
}

func (x *CheckPolicyResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckPolicyResponse) GetMatchedRules() []string {
	if x != nil {
		return x.MatchedRules
	}
	return nil
}

func (x *CheckPolicyResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CompilePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Requester     string                 `protobuf:"bytes,2,opt,name=requester,proto3" json:"requester,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompilePolicyRequest) Reset() {
	*x = CompilePolicyRequest{}
	mi := &file_authen_v1_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompilePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompilePolicyRequest) ProtoMessage() {}

func (x *CompilePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompilePolicyRequest.ProtoReflect.Descriptor instead.
func (*CompilePolicyRequest) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{19}
}

func (x *CompilePolicyRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CompilePolicyRequest) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

type CompilePolicyResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProposalId      string                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	Rules           []*CompiledRule        `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // pending / rejected
	RejectionReason string                 `protobuf:"bytes,4,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompilePolicyResponse) Reset() {
	*x = CompilePolicyResponse{}
	mi := &file_authen_v1_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompilePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompilePolicyResponse) ProtoMessage() {}

func (x *CompilePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompilePolicyResponse.ProtoReflect.Descriptor instead.
func (*CompilePolicyResponse) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{20}
}

func (x *CompilePolicyResponse) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *CompilePolicyResponse) GetRules() []*CompiledRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *CompilePolicyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CompilePolicyResponse) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

type CompiledRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Condition     string                 `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompiledRule) Reset() {
	*x = CompiledRule{}
	mi := &file_authen_v1_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompiledRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompiledRule) ProtoMessage() {}

func (x *CompiledRule) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompiledRule.ProtoReflect.Descriptor instead.
func (*CompiledRule) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{21}
}

func (x *CompiledRule) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CompiledRule) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CompiledRule) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CompiledRule) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

type ListProposalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProposalsRequest) Reset() {
	*x = ListProposalsRequest{}
	mi := &file_authen_v1_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProposalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProposalsRequest) ProtoMessage() {}

func (x *ListProposalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProposalsRequest.ProtoReflect.Descriptor instead.
func (*ListProposalsRequest) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{22}
}

func (x *ListProposalsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListProposalsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ProposalInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NlInput         string                 `protobuf:"bytes,2,opt,name=nl_input,json=nlInput,proto3" json:"nl_input,omitempty"`
	CompiledRules   []*CompiledRule        `protobuf:"bytes,3,rep,name=compiled_rules,json=compiledRules,proto3" json:"compiled_rules,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // pending / approved / rejected
	RejectionReason string                 `protobuf:"bytes,5,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	ProposedBy      string                 `protobuf:"bytes,6,opt,name=proposed_by,json=proposedBy,proto3" json:"proposed_by,omitempty"`
	ApprovedBy      string                 `protobuf:"bytes,7,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProposalInfo) Reset() {
	*x = ProposalInfo{}
	mi := &file_authen_v1_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalInfo) ProtoMessage() {}

func (x *ProposalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalInfo.ProtoReflect.Descriptor instead.
func (*ProposalInfo) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{23}
}

func (x *ProposalInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProposalInfo) GetNlInput() string {
	if x != nil {
		return x.NlInput
	}
	return ""
}

func (x *ProposalInfo) GetCompiledRules() []*CompiledRule {
	if x != nil {
		return x.CompiledRules
	}
	return nil
}

func (x *ProposalInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProposalInfo) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *ProposalInfo) GetProposedBy() string {
	if x != nil {
		return x.ProposedBy
	}
	return ""
}

func (x *ProposalInfo) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

func (x *ProposalInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ProposalInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ProposalList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proposals     []*ProposalInfo        `protobuf:"bytes,1,rep,name=proposals,proto3" json:"proposals,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposalList) Reset() {
	*x = ProposalList{}
	mi := &file_authen_v1_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalList) ProtoMessage() {}

func (x *ProposalList) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalList.ProtoReflect.Descriptor instead.
func (*ProposalList) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{24}
}

func (x *ProposalList) GetProposals() []*ProposalInfo {
	if x != nil {
		return x.Proposals
	}
	return nil
}

func (x *ProposalList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ApproveProposalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    string                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	Approver      string                 `protobuf:"bytes,2,opt,name=approver,proto3" json:"approver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveProposalRequest) Reset() {
	*x = ApproveProposalRequest{}
	mi := &file_authen_v1_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveProposalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveProposalRequest) ProtoMessage() {}

func (x *ApproveProposalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveProposalRequest.ProtoReflect.Descriptor instead.
func (*ApproveProposalRequest) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{25}
}

func (x *ApproveProposalRequest) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *ApproveProposalRequest) GetApprover() string {
	if x != nil {
		return x.Approver
	}
	return ""
}

type ApproveProposalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyId      string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveProposalResponse) Reset() {
	*x = ApproveProposalResponse{}
	mi := &file_authen_v1_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveProposalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveProposalResponse) ProtoMessage() {}

func (x *ApproveProposalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveProposalResponse.ProtoReflect.Descriptor instead.
func (*ApproveProposalResponse) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{26}
}

func (x *ApproveProposalResponse) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *ApproveProposalResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetServerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerInfoRequest) Reset() {
	*x = GetServerInfoRequest{}
	mi := &file_authen_v1_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoRequest) ProtoMessage() {}

func (x *GetServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoRequest.ProtoReflect.Descriptor instead.
func (*GetServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{27}
}

type ServerInfo struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Version              string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ProtocolVersion      string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	StorageBackend       string                 `protobuf:"bytes,3,opt,name=storage_backend,json=storageBackend,proto3" json:"storage_backend,omitempty"`
	UptimeSeconds        int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ActiveSessions       int32                  `protobuf:"varint,5,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	RegisteredIdentities int32                  `protobuf:"varint,6,opt,name=registered_identities,json=registeredIdentities,proto3" json:"registered_identities,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_authen_v1_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{28}
}

func (x *ServerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerInfo) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *ServerInfo) GetStorageBackend() string {
	if x != nil {
		return x.StorageBackend
	}
	return ""
}

func (x *ServerInfo) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *ServerInfo) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *ServerInfo) GetRegisteredIdentities() int32 {
	if x != nil {
		return x.RegisteredIdentities
	}
	return 0
}

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	IdentityId    string                 `protobuf:"bytes,2,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	KeyId         string                 `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Label         string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	IpAddress     string                 `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,6,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt    int64                  `protobuf:"varint,8,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_authen_v1_admin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{29}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *SessionInfo) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SessionInfo) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SessionInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *SessionInfo) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *SessionInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SessionInfo) GetLastUsedAt() int64 {
	if x != nil {
		return x.LastUsedAt
	}
	return 0
}

func (x *SessionInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	IdentityId    string                 `protobuf:"bytes,2,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_authen_v1_admin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{30}
}

func (x *ListSessionsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListSessionsRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *ListSessionsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SessionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionList) Reset() {
	*x = SessionList{}
	mi := &file_authen_v1_admin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionList) ProtoMessage() {}

func (x *SessionList) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionList.ProtoReflect.Descriptor instead.
func (*SessionList) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{31}
}

func (x *SessionList) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *SessionList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RevokeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionRequest) Reset() {
	*x = RevokeSessionRequest{}
	mi := &file_authen_v1_admin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest) ProtoMessage() {}

func (x *RevokeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionRequest.ProtoReflect.Descriptor instead.
func (*RevokeSessionRequest) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{32}
}

func (x *RevokeSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RevokeSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionResponse) Reset() {
	*x = RevokeSessionResponse{}
	mi := &file_authen_v1_admin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionResponse) ProtoMessage() {}

func (x *RevokeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionResponse.ProtoReflect.Descriptor instead.
func (*RevokeSessionResponse) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{33}
}

type ApproveIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveIdentityRequest) Reset() {
	*x = ApproveIdentityRequest{}
	mi := &file_authen_v1_admin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveIdentityRequest) ProtoMessage() {}

func (x *ApproveIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveIdentityRequest.ProtoReflect.Descriptor instead.
func (*ApproveIdentityRequest) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{34}
}

func (x *ApproveIdentityRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ApproveIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveIdentityResponse) Reset() {
	*x = ApproveIdentityResponse{}
	mi := &file_authen_v1_admin_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveIdentityResponse) ProtoMessage() {}

func (x *ApproveIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveIdentityResponse.ProtoReflect.Descriptor instead.
func (*ApproveIdentityResponse) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{35}
}

func (x *ApproveIdentityResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ApproveIdentityResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RejectIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectIdentityRequest) Reset() {
	*x = RejectIdentityRequest{}
	mi := &file_authen_v1_admin_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectIdentityRequest) ProtoMessage() {}

func (x *RejectIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectIdentityRequest.ProtoReflect.Descriptor instead.
func (*RejectIdentityRequest) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{36}
}

func (x *RejectIdentityRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type RejectIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectIdentityResponse) Reset() {
	*x = RejectIdentityResponse{}
	mi := &file_authen_v1_admin_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectIdentityResponse) ProtoMessage() {}

func (x *RejectIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectIdentityResponse.ProtoReflect.Descriptor instead.
func (*RejectIdentityResponse) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{37}
}

type IssuePassportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"` // Duration in seconds (default: 86400 = 24h)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuePassportRequest) Reset() {
	*x = IssuePassportRequest{}
	mi := &file_authen_v1_admin_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuePassportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuePassportRequest) ProtoMessage() {}

func (x *IssuePassportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuePassportRequest.ProtoReflect.Descriptor instead.
func (*IssuePassportRequest) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{38}
}

func (x *IssuePassportRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *IssuePassportRequest) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type IssuePassportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	KeyId         string                 `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuePassportResponse) Reset() {
	*x = IssuePassportResponse{}
	mi := &file_authen_v1_admin_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuePassportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuePassportResponse) ProtoMessage() {}

func (x *IssuePassportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authen_v1_admin_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuePassportResponse.ProtoReflect.Descriptor instead.
func (*IssuePassportResponse) Descriptor() ([]byte, []int) {
	return file_authen_v1_admin_proto_rawDescGZIP(), []int{39}
}

func (x *IssuePassportResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *IssuePassportResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *IssuePassportResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

var File_authen_v1_admin_proto protoreflect.FileDescriptor

const file_authen_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x15authen/v1/admin.proto\x12\tauthen.v1\x1a\x16authen/v1/common.proto\"\xb7\x01\n" +
	"\x14IssueRegTokenRequest\x12\x19\n" +
	"\bmax_uses\x18\x01 \x01(\x05R\amaxUses\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\x12\x14\n" +
	"\x05label\x18\x05 \x01(\tR\x05label\x12!\n" +
	"\fauto_approve\x18\x06 \x01(\bR\vautoApprove\"\x92\x02\n" +
	"\bRegToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12%\n" +
	"\x0eremaining_uses\x18\x02 \x01(\x05R\rremainingUses\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\x12\x14\n" +
	"\x05roles\x18\x05 \x03(\tR\x05roles\x12\x14\n" +
	"\x05label\x18\x06 \x01(\tR\x05label\x12\x0e\n" +
	"\x02id\x18\a \x01(\tR\x02id\x12\x18\n" +
	"\arevoked\x18\b \x01(\bR\arevoked\x12!\n" +
	"\fauto_approve\x18\t \x01(\bR\vautoApprove\x12\x19\n" +
	"\bmax_uses\x18\n" +
	" \x01(\x05R\amaxUses\"M\n" +
	"\x14ListRegTokensRequest\x125\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x15.authen.v1.PaginationR\n" +
	"pagination\"Q\n" +
	"\fRegTokenList\x12+\n" +
	"\x06tokens\x18\x01 \x03(\v2\x13.authen.v1.RegTokenR\x06tokens\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"'\n" +
	"\x15RevokeRegTokenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16RevokeRegTokenResponse\"\xd4\x01\n" +
	"\rPublicKeyInfo\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x19\n" +
	"\bkey_type\x18\x02 \x01(\tR\akeyType\x12\x1f\n" +
	"\videntity_id\x18\x03 \x01(\tR\n" +
	"identityId\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12#\n" +
	"\rregistered_at\x18\x05 \x01(\x03R\fregisteredAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x03R\texpiresAt\"\x81\x01\n" +
	"\x0fListKeysRequest\x125\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x15.authen.v1.PaginationR\n" +
	"pagination\x12\x1f\n" +
	"\videntity_id\x18\x02 \x01(\tR\n" +
	"identityId\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\"M\n" +
	"\aKeyList\x12,\n" +
	"\x04keys\x18\x01 \x03(\v2\x18.authen.v1.PublicKeyInfoR\x04keys\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\")\n" +
	"\x10DeleteKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\"\x13\n" +
	"\x11DeleteKeyResponse\"r\n" +
	"\n" +
	"PolicyRule\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x1c\n" +
	"\tcondition\x18\x04 \x01(\tR\tcondition\"w\n" +
	"\x12ApplyPolicyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12+\n" +
	"\x05rules\x18\x03 \x03(\v2\x15.authen.v1.PolicyRuleR\x05rules\"2\n" +
	"\x13ApplyPolicyResponse\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\"L\n" +
	"\x13ListPoliciesRequest\x125\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x15.authen.v1.PaginationR\n" +
	"pagination\"\xbd\x01\n" +
	"\n" +
	"PolicyInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12+\n" +
	"\x05rules\x18\x04 \x03(\v2\x15.authen.v1.PolicyRuleR\x05rules\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"U\n" +
	"\n" +
	"PolicyList\x121\n" +
	"\bpolicies\x18\x01 \x03(\v2\x15.authen.v1.PolicyInfoR\bpolicies\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xeb\x01\n" +
	"\x12CheckPolicyRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12D\n" +
	"\acontext\x18\x04 \x03(\v2*.authen.v1.CheckPolicyRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\x13CheckPolicyResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12#\n" +
	"\rmatched_rules\x18\x02 \x03(\tR\fmatchedRules\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"L\n" +
	"\x14CompilePolicyRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x1c\n" +
	"\trequester\x18\x02 \x01(\tR\trequester\"\xaa\x01\n" +
	"\x15CompilePolicyResponse\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\x12-\n" +
	"\x05rules\x18\x02 \x03(\v2\x17.authen.v1.CompiledRuleR\x05rules\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12)\n" +
	"\x10rejection_reason\x18\x04 \x01(\tR\x0frejectionReason\"t\n" +
	"\fCompiledRule\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x1c\n" +
	"\tcondition\x18\x04 \x01(\tR\tcondition\"e\n" +
	"\x14ListProposalsRequest\x125\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x15.authen.v1.PaginationR\n" +
	"pagination\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xbc\x02\n" +
	"\fProposalInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bnl_input\x18\x02 \x01(\tR\anlInput\x12>\n" +
	"\x0ecompiled_rules\x18\x03 \x03(\v2\x17.authen.v1.CompiledRuleR\rcompiledRules\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12)\n" +
	"\x10rejection_reason\x18\x05 \x01(\tR\x0frejectionReason\x12\x1f\n" +
	"\vproposed_by\x18\x06 \x01(\tR\n" +
	"proposedBy\x12\x1f\n" +
	"\vapproved_by\x18\a \x01(\tR\n" +
	"approvedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\"[\n" +
	"\fProposalList\x125\n" +
	"\tproposals\x18\x01 \x03(\v2\x17.authen.v1.ProposalInfoR\tproposals\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"U\n" +
	"\x16ApproveProposalRequest\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\x12\x1a\n" +
	"\bapprover\x18\x02 \x01(\tR\bapprover\"N\n" +
	"\x17ApproveProposalResponse\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x16\n" +
	"\x14GetServerInfoRequest\"\xff\x01\n" +
	"\n" +
	"ServerInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x12'\n" +
	"\x0fstorage_backend\x18\x03 \x01(\tR\x0estorageBackend\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\x12'\n" +
	"\x0factive_sessions\x18\x05 \x01(\x05R\x0eactiveSessions\x123\n" +
	"\x15registered_identities\x18\x06 \x01(\x05R\x14registeredIdentities\"\x91\x02\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\videntity_id\x18\x02 \x01(\tR\n" +
	"identityId\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x05 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x06 \x01(\tR\tuserAgent\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12 \n" +
	"\flast_used_at\x18\b \x01(\x03R\n" +
	"lastUsedAt\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\"\x85\x01\n" +
	"\x13ListSessionsRequest\x125\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x15.authen.v1.PaginationR\n" +
	"pagination\x12\x1f\n" +
	"\videntity_id\x18\x02 \x01(\tR\n" +
	"identityId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"W\n" +
	"\vSessionList\x122\n" +
	"\bsessions\x18\x01 \x03(\v2\x16.authen.v1.SessionInfoR\bsessions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"5\n" +
	"\x14RevokeSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x17\n" +
	"\x15RevokeSessionResponse\",\n" +
	"\x16ApproveIdentityRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"H\n" +
	"\x17ApproveIdentityResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"+\n" +
	"\x15RejectIdentityRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x18\n" +
	"\x16RejectIdentityResponse\"L\n" +
	"\x14IssuePassportRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x05R\texpiresIn\"c\n" +
	"\x15IssuePassportResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x05R\texpiresIn\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId2\xc1\n" +
	"\n" +
	"\fAdminService\x12E\n" +
	"\rIssueRegToken\x12\x1f.authen.v1.IssueRegTokenRequest\x1a\x13.authen.v1.RegToken\x12I\n" +
	"\rListRegTokens\x12\x1f.authen.v1.ListRegTokensRequest\x1a\x17.authen.v1.RegTokenList\x12U\n" +
	"\x0eRevokeRegToken\x12 .authen.v1.RevokeRegTokenRequest\x1a!.authen.v1.RevokeRegTokenResponse\x12X\n" +
	"\x0fApproveIdentity\x12!.authen.v1.ApproveIdentityRequest\x1a\".authen.v1.ApproveIdentityResponse\x12U\n" +
	"\x0eRejectIdentity\x12 .authen.v1.RejectIdentityRequest\x1a!.authen.v1.RejectIdentityResponse\x12:\n" +
	"\bListKeys\x12\x1a.authen.v1.ListKeysRequest\x1a\x12.authen.v1.KeyList\x12F\n" +
	"\tDeleteKey\x12\x1b.authen.v1.DeleteKeyRequest\x1a\x1c.authen.v1.DeleteKeyResponse\x12L\n" +
	"\vApplyPolicy\x12\x1d.authen.v1.ApplyPolicyRequest\x1a\x1e.authen.v1.ApplyPolicyResponse\x12E\n" +
	"\fListPolicies\x12\x1e.authen.v1.ListPoliciesRequest\x1a\x15.authen.v1.PolicyList\x12L\n" +
	"\vCheckPolicy\x12\x1d.authen.v1.CheckPolicyRequest\x1a\x1e.authen.v1.CheckPolicyResponse\x12R\n" +
	"\rCompilePolicy\x12\x1f.authen.v1.CompilePolicyRequest\x1a .authen.v1.CompilePolicyResponse\x12I\n" +
	"\rListProposals\x12\x1f.authen.v1.ListProposalsRequest\x1a\x17.authen.v1.ProposalList\x12X\n" +
	"\x0fApproveProposal\x12!.authen.v1.ApproveProposalRequest\x1a\".authen.v1.ApproveProposalResponse\x12G\n" +
	"\rGetServerInfo\x12\x1f.authen.v1.GetServerInfoRequest\x1a\x15.authen.v1.ServerInfo\x12F\n" +
	"\fListSessions\x12\x1e.authen.v1.ListSessionsRequest\x1a\x16.authen.v1.SessionList\x12R\n" +
	"\rRevokeSession\x12\x1f.authen.v1.RevokeSessionRequest\x1a .authen.v1.RevokeSessionResponse\x12R\n" +
	"\rIssuePassport\x12\x1f.authen.v1.IssuePassportRequest\x1a .authen.v1.IssuePassportResponseB<Z:github.com/jonathan-chery/authen-proto/pkg/proto/authen/v1b\x06proto3"

var (
	file_authen_v1_admin_proto_rawDescOnce sync.Once
	file_authen_v1_admin_proto_rawDescData []byte
)

func file_authen_v1_admin_proto_rawDescGZIP() []byte {
	file_authen_v1_admin_proto_rawDescOnce.Do(func() {
		file_authen_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authen_v1_admin_proto_rawDesc), len(file_authen_v1_admin_proto_rawDesc)))
	})
	return file_authen_v1_admin_proto_rawDescData
}

var file_authen_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_authen_v1_admin_proto_goTypes = []any{
	(*IssueRegTokenRequest)(nil),    // 0: authen.v1.IssueRegTokenRequest
	(*RegToken)(nil),                // 1: authen.v1.RegToken
	(*ListRegTokensRequest)(nil),    // 2: authen.v1.ListRegTokensRequest
	(*RegTokenList)(nil),            // 3: authen.v1.RegTokenList
	(*RevokeRegTokenRequest)(nil),   // 4: authen.v1.RevokeRegTokenRequest
	(*RevokeRegTokenResponse)(nil),  // 5: authen.v1.RevokeRegTokenResponse
	(*PublicKeyInfo)(nil),           // 6: authen.v1.PublicKeyInfo
	(*ListKeysRequest)(nil),         // 7: authen.v1.ListKeysRequest
	(*KeyList)(nil),                 // 8: authen.v1.KeyList
	(*DeleteKeyRequest)(nil),        // 9: authen.v1.DeleteKeyRequest
	(*DeleteKeyResponse)(nil),       // 10: authen.v1.DeleteKeyResponse
	(*PolicyRule)(nil),              // 11: authen.v1.PolicyRule
	(*ApplyPolicyRequest)(nil),      // 12: authen.v1.ApplyPolicyRequest
	(*ApplyPolicyResponse)(nil),     // 13: authen.v1.ApplyPolicyResponse
	(*ListPoliciesRequest)(nil),     // 14: authen.v1.ListPoliciesRequest
	(*PolicyInfo)(nil),              // 15: authen.v1.PolicyInfo
	(*PolicyList)(nil),              // 16: authen.v1.PolicyList
	(*CheckPolicyRequest)(nil),      // 17: authen.v1.CheckPolicyRequest
	(*CheckPolicyResponse)(nil),     // 18: authen.v1.CheckPolicyResponse
	(*CompilePolicyRequest)(nil),    // 19: authen.v1.CompilePolicyRequest
	(*CompilePolicyResponse)(nil),   // 20: authen.v1.CompilePolicyResponse
	(*CompiledRule)(nil),            // 21: authen.v1.CompiledRule
	(*ListProposalsRequest)(nil),    // 22: authen.v1.ListProposalsRequest
	(*ProposalInfo)(nil),            // 23: authen.v1.ProposalInfo
	(*ProposalList)(nil),            // 24: authen.v1.ProposalList
	(*ApproveProposalRequest)(nil),  // 25: authen.v1.ApproveProposalRequest
	(*ApproveProposalResponse)(nil), // 26: authen.v1.ApproveProposalResponse
	(*GetServerInfoRequest)(nil),    // 27: authen.v1.GetServerInfoRequest
	(*ServerInfo)(nil),              // 28: authen.v1.ServerInfo
	(*SessionInfo)(nil),             // 29: authen.v1.SessionInfo
	(*ListSessionsRequest)(nil),     // 30: authen.v1.ListSessionsRequest
	(*SessionList)(nil),             // 31: authen.v1.SessionList
	(*RevokeSessionRequest)(nil),    // 32: authen.v1.RevokeSessionRequest
	(*RevokeSessionResponse)(nil),   // 33: authen.v1.RevokeSessionResponse
	(*ApproveIdentityRequest)(nil),  // 34: authen.v1.ApproveIdentityRequest
	(*ApproveIdentityResponse)(nil), // 35: authen.v1.ApproveIdentityResponse
	(*RejectIdentityRequest)(nil),   // 36: authen.v1.RejectIdentityRequest
	(*RejectIdentityResponse)(nil),  // 37: authen.v1.RejectIdentityResponse
	(*IssuePassportRequest)(nil),    // 38: authen.v1.IssuePassportRequest
	(*IssuePassportResponse)(nil),   // 39: authen.v1.IssuePassportResponse
	nil,                             // 40: authen.v1.CheckPolicyRequest.ContextEntry
	(*Pagination)(nil),              // 41: authen.v1.Pagination
}
var file_authen_v1_admin_proto_depIdxs = []int32{
	41, // 0: authen.v1.ListRegTokensRequest.pagination:type_name -> authen.v1.Pagination
	1,  // 1: authen.v1.RegTokenList.tokens:type_name -> authen.v1.RegToken
	41, // 2: authen.v1.ListKeysRequest.pagination:type_name -> authen.v1.Pagination
	6,  // 3: authen.v1.KeyList.keys:type_name -> authen.v1.PublicKeyInfo
	11, // 4: authen.v1.ApplyPolicyRequest.rules:type_name -> authen.v1.PolicyRule
	41, // 5: authen.v1.ListPoliciesRequest.pagination:type_name -> authen.v1.Pagination
	11, // 6: authen.v1.PolicyInfo.rules:type_name -> authen.v1.PolicyRule
	15, // 7: authen.v1.PolicyList.policies:type_name -> authen.v1.PolicyInfo
	40, // 8: authen.v1.CheckPolicyRequest.context:type_name -> authen.v1.CheckPolicyRequest.ContextEntry
	21, // 9: authen.v1.CompilePolicyResponse.rules:type_name -> authen.v1.CompiledRule
	41, // 10: authen.v1.ListProposalsRequest.pagination:type_name -> authen.v1.Pagination
	21, // 11: authen.v1.ProposalInfo.compiled_rules:type_name -> authen.v1.CompiledRule
	23, // 12: authen.v1.ProposalList.proposals:type_name -> authen.v1.ProposalInfo
	41, // 13: authen.v1.ListSessionsRequest.pagination:type_name -> authen.v1.Pagination
	29, // 14: authen.v1.SessionList.sessions:type_name -> authen.v1.SessionInfo
	0,  // 15: authen.v1.AdminService.IssueRegToken:input_type -> authen.v1.IssueRegTokenRequest
	2,  // 16: authen.v1.AdminService.ListRegTokens:input_type -> authen.v1.ListRegTokensRequest
	4,  // 17: authen.v1.AdminService.RevokeRegToken:input_type -> authen.v1.RevokeRegTokenRequest
	34, // 18: authen.v1.AdminService.ApproveIdentity:input_type -> authen.v1.ApproveIdentityRequest
	36, // 19: authen.v1.AdminService.RejectIdentity:input_type -> authen.v1.RejectIdentityRequest
	7,  // 20: authen.v1.AdminService.ListKeys:input_type -> authen.v1.ListKeysRequest
	9,  // 21: authen.v1.AdminService.DeleteKey:input_type -> authen.v1.DeleteKeyRequest
	12, // 22: authen.v1.AdminService.ApplyPolicy:input_type -> authen.v1.ApplyPolicyRequest
	14, // 23: authen.v1.AdminService.ListPolicies:input_type -> authen.v1.ListPoliciesRequest
	17, // 24: authen.v1.AdminService.CheckPolicy:input_type -> authen.v1.CheckPolicyRequest
	19, // 25: authen.v1.AdminService.CompilePolicy:input_type -> authen.v1.CompilePolicyRequest
	22, // 26: authen.v1.AdminService.ListProposals:input_type -> authen.v1.ListProposalsRequest
	25, // 27: authen.v1.AdminService.ApproveProposal:input_type -> authen.v1.ApproveProposalRequest
	27, // 28: authen.v1.AdminService.GetServerInfo:input_type -> authen.v1.GetServerInfoRequest
	30, // 29: authen.v1.AdminService.ListSessions:input_type -> authen.v1.ListSessionsRequest
	32, // 30: authen.v1.AdminService.RevokeSession:input_type -> authen.v1.RevokeSessionRequest
	38, // 31: authen.v1.AdminService.IssuePassport:input_type -> authen.v1.IssuePassportRequest
	1,  // 32: authen.v1.AdminService.IssueRegToken:output_type -> authen.v1.RegToken
	3,  // 33: authen.v1.AdminService.ListRegTokens:output_type -> authen.v1.RegTokenList
	5,  // 34: authen.v1.AdminService.RevokeRegToken:output_type -> authen.v1.RevokeRegTokenResponse
	35, // 35: authen.v1.AdminService.ApproveIdentity:output_type -> authen.v1.ApproveIdentityResponse
	37, // 36: authen.v1.AdminService.RejectIdentity:output_type -> authen.v1.RejectIdentityResponse
	8,  // 37: authen.v1.AdminService.ListKeys:output_type -> authen.v1.KeyList
	10, // 38: authen.v1.AdminService.DeleteKey:output_type -> authen.v1.DeleteKeyResponse
	13, // 39: authen.v1.AdminService.ApplyPolicy:output_type -> authen.v1.ApplyPolicyResponse
	16, // 40: authen.v1.AdminService.ListPolicies:output_type -> authen.v1.PolicyList
	18, // 41: authen.v1.AdminService.CheckPolicy:output_type -> authen.v1.CheckPolicyResponse
	20, // 42: authen.v1.AdminService.CompilePolicy:output_type -> authen.v1.CompilePolicyResponse
	24, // 43: authen.v1.AdminService.ListProposals:output_type -> authen.v1.ProposalList
	26, // 44: authen.v1.AdminService.ApproveProposal:output_type -> authen.v1.ApproveProposalResponse
	28, // 45: authen.v1.AdminService.GetServerInfo:output_type -> authen.v1.ServerInfo
	31, // 46: authen.v1.AdminService.ListSessions:output_type -> authen.v1.SessionList
	33, // 47: authen.v1.AdminService.RevokeSession:output_type -> authen.v1.RevokeSessionResponse
	39, // 48: authen.v1.AdminService.IssuePassport:output_type -> authen.v1.IssuePassportResponse
	32, // [32:49] is the sub-list for method output_type
	15, // [15:32] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_authen_v1_admin_proto_init() }
func file_authen_v1_admin_proto_init() {
	if File_authen_v1_admin_proto != nil {
		return
	}
	file_authen_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authen_v1_admin_proto_rawDesc), len(file_authen_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authen_v1_admin_proto_goTypes,
		DependencyIndexes: file_authen_v1_admin_proto_depIdxs,
		MessageInfos:      file_authen_v1_admin_proto_msgTypes,
	}.Build()
	File_authen_v1_admin_proto = out.File
	file_authen_v1_admin_proto_goTypes = nil
	file_authen_v1_admin_proto_depIdxs = nil
}
