// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: authen/v1/admin.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_IssueRegToken_FullMethodName   = "/authen.v1.AdminService/IssueRegToken"
	AdminService_ListRegTokens_FullMethodName   = "/authen.v1.AdminService/ListRegTokens"
	AdminService_RevokeRegToken_FullMethodName  = "/authen.v1.AdminService/RevokeRegToken"
	AdminService_ApproveIdentity_FullMethodName = "/authen.v1.AdminService/ApproveIdentity"
	AdminService_RejectIdentity_FullMethodName  = "/authen.v1.AdminService/RejectIdentity"
	AdminService_ListKeys_FullMethodName        = "/authen.v1.AdminService/ListKeys"
	AdminService_DeleteKey_FullMethodName       = "/authen.v1.AdminService/DeleteKey"
	AdminService_ApplyPolicy_FullMethodName     = "/authen.v1.AdminService/ApplyPolicy"
	AdminService_ListPolicies_FullMethodName    = "/authen.v1.AdminService/ListPolicies"
	AdminService_CheckPolicy_FullMethodName     = "/authen.v1.AdminService/CheckPolicy"
	AdminService_GetServerInfo_FullMethodName   = "/authen.v1.AdminService/GetServerInfo"
	AdminService_ListSessions_FullMethodName    = "/authen.v1.AdminService/ListSessions"
	AdminService_RevokeSession_FullMethodName   = "/authen.v1.AdminService/RevokeSession"
	AdminService_IssuePassport_FullMethodName   = "/authen.v1.AdminService/IssuePassport"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminServiceClient interface {
	IssueRegToken(ctx context.Context, in *IssueRegTokenRequest, opts ...grpc.CallOption) (*RegToken, error)
	ListRegTokens(ctx context.Context, in *ListRegTokensRequest, opts ...grpc.CallOption) (*RegTokenList, error)
	RevokeRegToken(ctx context.Context, in *RevokeRegTokenRequest, opts ...grpc.CallOption) (*RevokeRegTokenResponse, error)
	ApproveIdentity(ctx context.Context, in *ApproveIdentityRequest, opts ...grpc.CallOption) (*ApproveIdentityResponse, error)
	RejectIdentity(ctx context.Context, in *RejectIdentityRequest, opts ...grpc.CallOption) (*RejectIdentityResponse, error)
	ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*KeyList, error)
	DeleteKey(ctx context.Context, in *DeleteKeyRequest, opts ...grpc.CallOption) (*DeleteKeyResponse, error)
	ApplyPolicy(ctx context.Context, in *ApplyPolicyRequest, opts ...grpc.CallOption) (*ApplyPolicyResponse, error)
	ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*PolicyList, error)
	CheckPolicy(ctx context.Context, in *CheckPolicyRequest, opts ...grpc.CallOption) (*CheckPolicyResponse, error)
	GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*ServerInfo, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*SessionList, error)
	RevokeSession(ctx context.Context, in *RevokeSessionRequest, opts ...grpc.CallOption) (*RevokeSessionResponse, error)
	IssuePassport(ctx context.Context, in *IssuePassportRequest, opts ...grpc.CallOption) (*IssuePassportResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) IssueRegToken(ctx context.Context, in *IssueRegTokenRequest, opts ...grpc.CallOption) (*RegToken, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegToken)
	err := c.cc.Invoke(ctx, AdminService_IssueRegToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListRegTokens(ctx context.Context, in *ListRegTokensRequest, opts ...grpc.CallOption) (*RegTokenList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegTokenList)
	err := c.cc.Invoke(ctx, AdminService_ListRegTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RevokeRegToken(ctx context.Context, in *RevokeRegTokenRequest, opts ...grpc.CallOption) (*RevokeRegTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeRegTokenResponse)
	err := c.cc.Invoke(ctx, AdminService_RevokeRegToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ApproveIdentity(ctx context.Context, in *ApproveIdentityRequest, opts ...grpc.CallOption) (*ApproveIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveIdentityResponse)
	err := c.cc.Invoke(ctx, AdminService_ApproveIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RejectIdentity(ctx context.Context, in *RejectIdentityRequest, opts ...grpc.CallOption) (*RejectIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectIdentityResponse)
	err := c.cc.Invoke(ctx, AdminService_RejectIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*KeyList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyList)
	err := c.cc.Invoke(ctx, AdminService_ListKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeleteKey(ctx context.Context, in *DeleteKeyRequest, opts ...grpc.CallOption) (*DeleteKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteKeyResponse)
	err := c.cc.Invoke(ctx, AdminService_DeleteKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ApplyPolicy(ctx context.Context, in *ApplyPolicyRequest, opts ...grpc.CallOption) (*ApplyPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyPolicyResponse)
	err := c.cc.Invoke(ctx, AdminService_ApplyPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*PolicyList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicyList)
	err := c.cc.Invoke(ctx, AdminService_ListPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CheckPolicy(ctx context.Context, in *CheckPolicyRequest, opts ...grpc.CallOption) (*CheckPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPolicyResponse)
	err := c.cc.Invoke(ctx, AdminService_CheckPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*ServerInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerInfo)
	err := c.cc.Invoke(ctx, AdminService_GetServerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*SessionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionList)
	err := c.cc.Invoke(ctx, AdminService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RevokeSession(ctx context.Context, in *RevokeSessionRequest, opts ...grpc.CallOption) (*RevokeSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeSessionResponse)
	err := c.cc.Invoke(ctx, AdminService_RevokeSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) IssuePassport(ctx context.Context, in *IssuePassportRequest, opts ...grpc.CallOption) (*IssuePassportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssuePassportResponse)
	err := c.cc.Invoke(ctx, AdminService_IssuePassport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
type AdminServiceServer interface {
	IssueRegToken(context.Context, *IssueRegTokenRequest) (*RegToken, error)
	ListRegTokens(context.Context, *ListRegTokensRequest) (*RegTokenList, error)
	RevokeRegToken(context.Context, *RevokeRegTokenRequest) (*RevokeRegTokenResponse, error)
	ApproveIdentity(context.Context, *ApproveIdentityRequest) (*ApproveIdentityResponse, error)
	RejectIdentity(context.Context, *RejectIdentityRequest) (*RejectIdentityResponse, error)
	ListKeys(context.Context, *ListKeysRequest) (*KeyList, error)
	DeleteKey(context.Context, *DeleteKeyRequest) (*DeleteKeyResponse, error)
	ApplyPolicy(context.Context, *ApplyPolicyRequest) (*ApplyPolicyResponse, error)
	ListPolicies(context.Context, *ListPoliciesRequest) (*PolicyList, error)
	CheckPolicy(context.Context, *CheckPolicyRequest) (*CheckPolicyResponse, error)
	GetServerInfo(context.Context, *GetServerInfoRequest) (*ServerInfo, error)
	ListSessions(context.Context, *ListSessionsRequest) (*SessionList, error)
	RevokeSession(context.Context, *RevokeSessionRequest) (*RevokeSessionResponse, error)
	IssuePassport(context.Context, *IssuePassportRequest) (*IssuePassportResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) IssueRegToken(context.Context, *IssueRegTokenRequest) (*RegToken, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueRegToken not implemented")
}
func (UnimplementedAdminServiceServer) ListRegTokens(context.Context, *ListRegTokensRequest) (*RegTokenList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRegTokens not implemented")
}
func (UnimplementedAdminServiceServer) RevokeRegToken(context.Context, *RevokeRegTokenRequest) (*RevokeRegTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeRegToken not implemented")
}
func (UnimplementedAdminServiceServer) ApproveIdentity(context.Context, *ApproveIdentityRequest) (*ApproveIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveIdentity not implemented")
}
func (UnimplementedAdminServiceServer) RejectIdentity(context.Context, *RejectIdentityRequest) (*RejectIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectIdentity not implemented")
}
func (UnimplementedAdminServiceServer) ListKeys(context.Context, *ListKeysRequest) (*KeyList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListKeys not implemented")
}
func (UnimplementedAdminServiceServer) DeleteKey(context.Context, *DeleteKeyRequest) (*DeleteKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteKey not implemented")
}
func (UnimplementedAdminServiceServer) ApplyPolicy(context.Context, *ApplyPolicyRequest) (*ApplyPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyPolicy not implemented")
}
func (UnimplementedAdminServiceServer) ListPolicies(context.Context, *ListPoliciesRequest) (*PolicyList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPolicies not implemented")
}
func (UnimplementedAdminServiceServer) CheckPolicy(context.Context, *CheckPolicyRequest) (*CheckPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckPolicy not implemented")
}
func (UnimplementedAdminServiceServer) GetServerInfo(context.Context, *GetServerInfoRequest) (*ServerInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerInfo not implemented")
}
func (UnimplementedAdminServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*SessionList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedAdminServiceServer) RevokeSession(context.Context, *RevokeSessionRequest) (*RevokeSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeSession not implemented")
}
func (UnimplementedAdminServiceServer) IssuePassport(context.Context, *IssuePassportRequest) (*IssuePassportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssuePassport not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_IssueRegToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueRegTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).IssueRegToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_IssueRegToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).IssueRegToken(ctx, req.(*IssueRegTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListRegTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRegTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListRegTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListRegTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListRegTokens(ctx, req.(*ListRegTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RevokeRegToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeRegTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RevokeRegToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RevokeRegToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RevokeRegToken(ctx, req.(*RevokeRegTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ApproveIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ApproveIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ApproveIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ApproveIdentity(ctx, req.(*ApproveIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RejectIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RejectIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RejectIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RejectIdentity(ctx, req.(*RejectIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListKeys(ctx, req.(*ListKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeleteKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeleteKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DeleteKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeleteKey(ctx, req.(*DeleteKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ApplyPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ApplyPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ApplyPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ApplyPolicy(ctx, req.(*ApplyPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListPolicies(ctx, req.(*ListPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CheckPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CheckPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_CheckPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CheckPolicy(ctx, req.(*CheckPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetServerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetServerInfo(ctx, req.(*GetServerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RevokeSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RevokeSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RevokeSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RevokeSession(ctx, req.(*RevokeSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_IssuePassport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssuePassportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).IssuePassport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_IssuePassport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).IssuePassport(ctx, req.(*IssuePassportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authen.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueRegToken",
			Handler:    _AdminService_IssueRegToken_Handler,
		},
		{
			MethodName: "ListRegTokens",
			Handler:    _AdminService_ListRegTokens_Handler,
		},
		{
			MethodName: "RevokeRegToken",
			Handler:    _AdminService_RevokeRegToken_Handler,
		},
		{
			MethodName: "ApproveIdentity",
			Handler:    _AdminService_ApproveIdentity_Handler,
		},
		{
			MethodName: "RejectIdentity",
			Handler:    _AdminService_RejectIdentity_Handler,
		},
		{
			MethodName: "ListKeys",
			Handler:    _AdminService_ListKeys_Handler,
		},
		{
			MethodName: "DeleteKey",
			Handler:    _AdminService_DeleteKey_Handler,
		},
		{
			MethodName: "ApplyPolicy",
			Handler:    _AdminService_ApplyPolicy_Handler,
		},
		{
			MethodName: "ListPolicies",
			Handler:    _AdminService_ListPolicies_Handler,
		},
		{
			MethodName: "CheckPolicy",
			Handler:    _AdminService_CheckPolicy_Handler,
		},
		{
			MethodName: "GetServerInfo",
			Handler:    _AdminService_GetServerInfo_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _AdminService_ListSessions_Handler,
		},
		{
			MethodName: "RevokeSession",
			Handler:    _AdminService_RevokeSession_Handler,
		},
		{
			MethodName: "IssuePassport",
			Handler:    _AdminService_IssuePassport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authen/v1/admin.proto",
}
