// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: authen/v1/admin.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/jonathan-chery/authen-proto/pkg/proto/authen/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AdminServiceName is the fully-qualified name of the AdminService service.
	AdminServiceName = "authen.v1.AdminService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AdminServiceIssueRegTokenProcedure is the fully-qualified name of the AdminService's
	// IssueRegToken RPC.
	AdminServiceIssueRegTokenProcedure = "/authen.v1.AdminService/IssueRegToken"
	// AdminServiceListRegTokensProcedure is the fully-qualified name of the AdminService's
	// ListRegTokens RPC.
	AdminServiceListRegTokensProcedure = "/authen.v1.AdminService/ListRegTokens"
	// AdminServiceRevokeRegTokenProcedure is the fully-qualified name of the AdminService's
	// RevokeRegToken RPC.
	AdminServiceRevokeRegTokenProcedure = "/authen.v1.AdminService/RevokeRegToken"
	// AdminServiceApproveIdentityProcedure is the fully-qualified name of the AdminService's
	// ApproveIdentity RPC.
	AdminServiceApproveIdentityProcedure = "/authen.v1.AdminService/ApproveIdentity"
	// AdminServiceRejectIdentityProcedure is the fully-qualified name of the AdminService's
	// RejectIdentity RPC.
	AdminServiceRejectIdentityProcedure = "/authen.v1.AdminService/RejectIdentity"
	// AdminServiceListKeysProcedure is the fully-qualified name of the AdminService's ListKeys RPC.
	AdminServiceListKeysProcedure = "/authen.v1.AdminService/ListKeys"
	// AdminServiceDeleteKeyProcedure is the fully-qualified name of the AdminService's DeleteKey RPC.
	AdminServiceDeleteKeyProcedure = "/authen.v1.AdminService/DeleteKey"
	// AdminServiceApplyPolicyProcedure is the fully-qualified name of the AdminService's ApplyPolicy
	// RPC.
	AdminServiceApplyPolicyProcedure = "/authen.v1.AdminService/ApplyPolicy"
	// AdminServiceListPoliciesProcedure is the fully-qualified name of the AdminService's ListPolicies
	// RPC.
	AdminServiceListPoliciesProcedure = "/authen.v1.AdminService/ListPolicies"
	// AdminServiceCheckPolicyProcedure is the fully-qualified name of the AdminService's CheckPolicy
	// RPC.
	AdminServiceCheckPolicyProcedure = "/authen.v1.AdminService/CheckPolicy"
	// AdminServiceGetServerInfoProcedure is the fully-qualified name of the AdminService's
	// GetServerInfo RPC.
	AdminServiceGetServerInfoProcedure = "/authen.v1.AdminService/GetServerInfo"
	// AdminServiceListSessionsProcedure is the fully-qualified name of the AdminService's ListSessions
	// RPC.
	AdminServiceListSessionsProcedure = "/authen.v1.AdminService/ListSessions"
	// AdminServiceRevokeSessionProcedure is the fully-qualified name of the AdminService's
	// RevokeSession RPC.
	AdminServiceRevokeSessionProcedure = "/authen.v1.AdminService/RevokeSession"
	// AdminServiceIssuePassportProcedure is the fully-qualified name of the AdminService's
	// IssuePassport RPC.
	AdminServiceIssuePassportProcedure = "/authen.v1.AdminService/IssuePassport"
)

// AdminServiceClient is a client for the authen.v1.AdminService service.
type AdminServiceClient interface {
	IssueRegToken(context.Context, *connect.Request[v1.IssueRegTokenRequest]) (*connect.Response[v1.RegToken], error)
	ListRegTokens(context.Context, *connect.Request[v1.ListRegTokensRequest]) (*connect.Response[v1.RegTokenList], error)
	RevokeRegToken(context.Context, *connect.Request[v1.RevokeRegTokenRequest]) (*connect.Response[v1.RevokeRegTokenResponse], error)
	ApproveIdentity(context.Context, *connect.Request[v1.ApproveIdentityRequest]) (*connect.Response[v1.ApproveIdentityResponse], error)
	RejectIdentity(context.Context, *connect.Request[v1.RejectIdentityRequest]) (*connect.Response[v1.RejectIdentityResponse], error)
	ListKeys(context.Context, *connect.Request[v1.ListKeysRequest]) (*connect.Response[v1.KeyList], error)
	DeleteKey(context.Context, *connect.Request[v1.DeleteKeyRequest]) (*connect.Response[v1.DeleteKeyResponse], error)
	ApplyPolicy(context.Context, *connect.Request[v1.ApplyPolicyRequest]) (*connect.Response[v1.ApplyPolicyResponse], error)
	ListPolicies(context.Context, *connect.Request[v1.ListPoliciesRequest]) (*connect.Response[v1.PolicyList], error)
	CheckPolicy(context.Context, *connect.Request[v1.CheckPolicyRequest]) (*connect.Response[v1.CheckPolicyResponse], error)
	GetServerInfo(context.Context, *connect.Request[v1.GetServerInfoRequest]) (*connect.Response[v1.ServerInfo], error)
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.SessionList], error)
	RevokeSession(context.Context, *connect.Request[v1.RevokeSessionRequest]) (*connect.Response[v1.RevokeSessionResponse], error)
	IssuePassport(context.Context, *connect.Request[v1.IssuePassportRequest]) (*connect.Response[v1.IssuePassportResponse], error)
}

// NewAdminServiceClient constructs a client for the authen.v1.AdminService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminServiceMethods := v1.File_authen_v1_admin_proto.Services().ByName("AdminService").Methods()
	return &adminServiceClient{
		issueRegToken: connect.NewClient[v1.IssueRegTokenRequest, v1.RegToken](
			httpClient,
			baseURL+AdminServiceIssueRegTokenProcedure,
			connect.WithSchema(adminServiceMethods.ByName("IssueRegToken")),
			connect.WithClientOptions(opts...),
		),
		listRegTokens: connect.NewClient[v1.ListRegTokensRequest, v1.RegTokenList](
			httpClient,
			baseURL+AdminServiceListRegTokensProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListRegTokens")),
			connect.WithClientOptions(opts...),
		),
		revokeRegToken: connect.NewClient[v1.RevokeRegTokenRequest, v1.RevokeRegTokenResponse](
			httpClient,
			baseURL+AdminServiceRevokeRegTokenProcedure,
			connect.WithSchema(adminServiceMethods.ByName("RevokeRegToken")),
			connect.WithClientOptions(opts...),
		),
		approveIdentity: connect.NewClient[v1.ApproveIdentityRequest, v1.ApproveIdentityResponse](
			httpClient,
			baseURL+AdminServiceApproveIdentityProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ApproveIdentity")),
			connect.WithClientOptions(opts...),
		),
		rejectIdentity: connect.NewClient[v1.RejectIdentityRequest, v1.RejectIdentityResponse](
			httpClient,
			baseURL+AdminServiceRejectIdentityProcedure,
			connect.WithSchema(adminServiceMethods.ByName("RejectIdentity")),
			connect.WithClientOptions(opts...),
		),
		listKeys: connect.NewClient[v1.ListKeysRequest, v1.KeyList](
			httpClient,
			baseURL+AdminServiceListKeysProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListKeys")),
			connect.WithClientOptions(opts...),
		),
		deleteKey: connect.NewClient[v1.DeleteKeyRequest, v1.DeleteKeyResponse](
			httpClient,
			baseURL+AdminServiceDeleteKeyProcedure,
			connect.WithSchema(adminServiceMethods.ByName("DeleteKey")),
			connect.WithClientOptions(opts...),
		),
		applyPolicy: connect.NewClient[v1.ApplyPolicyRequest, v1.ApplyPolicyResponse](
			httpClient,
			baseURL+AdminServiceApplyPolicyProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ApplyPolicy")),
			connect.WithClientOptions(opts...),
		),
		listPolicies: connect.NewClient[v1.ListPoliciesRequest, v1.PolicyList](
			httpClient,
			baseURL+AdminServiceListPoliciesProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListPolicies")),
			connect.WithClientOptions(opts...),
		),
		checkPolicy: connect.NewClient[v1.CheckPolicyRequest, v1.CheckPolicyResponse](
			httpClient,
			baseURL+AdminServiceCheckPolicyProcedure,
			connect.WithSchema(adminServiceMethods.ByName("CheckPolicy")),
			connect.WithClientOptions(opts...),
		),
		getServerInfo: connect.NewClient[v1.GetServerInfoRequest, v1.ServerInfo](
			httpClient,
			baseURL+AdminServiceGetServerInfoProcedure,
			connect.WithSchema(adminServiceMethods.ByName("GetServerInfo")),
			connect.WithClientOptions(opts...),
		),
		listSessions: connect.NewClient[v1.ListSessionsRequest, v1.SessionList](
			httpClient,
			baseURL+AdminServiceListSessionsProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListSessions")),
			connect.WithClientOptions(opts...),
		),
		revokeSession: connect.NewClient[v1.RevokeSessionRequest, v1.RevokeSessionResponse](
			httpClient,
			baseURL+AdminServiceRevokeSessionProcedure,
			connect.WithSchema(adminServiceMethods.ByName("RevokeSession")),
			connect.WithClientOptions(opts...),
		),
		issuePassport: connect.NewClient[v1.IssuePassportRequest, v1.IssuePassportResponse](
			httpClient,
			baseURL+AdminServiceIssuePassportProcedure,
			connect.WithSchema(adminServiceMethods.ByName("IssuePassport")),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminServiceClient implements AdminServiceClient.
type adminServiceClient struct {
	issueRegToken   *connect.Client[v1.IssueRegTokenRequest, v1.RegToken]
	listRegTokens   *connect.Client[v1.ListRegTokensRequest, v1.RegTokenList]
	revokeRegToken  *connect.Client[v1.RevokeRegTokenRequest, v1.RevokeRegTokenResponse]
	approveIdentity *connect.Client[v1.ApproveIdentityRequest, v1.ApproveIdentityResponse]
	rejectIdentity  *connect.Client[v1.RejectIdentityRequest, v1.RejectIdentityResponse]
	listKeys        *connect.Client[v1.ListKeysRequest, v1.KeyList]
	deleteKey       *connect.Client[v1.DeleteKeyRequest, v1.DeleteKeyResponse]
	applyPolicy     *connect.Client[v1.ApplyPolicyRequest, v1.ApplyPolicyResponse]
	listPolicies    *connect.Client[v1.ListPoliciesRequest, v1.PolicyList]
	checkPolicy     *connect.Client[v1.CheckPolicyRequest, v1.CheckPolicyResponse]
	getServerInfo   *connect.Client[v1.GetServerInfoRequest, v1.ServerInfo]
	listSessions    *connect.Client[v1.ListSessionsRequest, v1.SessionList]
	revokeSession   *connect.Client[v1.RevokeSessionRequest, v1.RevokeSessionResponse]
	issuePassport   *connect.Client[v1.IssuePassportRequest, v1.IssuePassportResponse]
}

// IssueRegToken calls authen.v1.AdminService.IssueRegToken.
func (c *adminServiceClient) IssueRegToken(ctx context.Context, req *connect.Request[v1.IssueRegTokenRequest]) (*connect.Response[v1.RegToken], error) {
	return c.issueRegToken.CallUnary(ctx, req)
}

// ListRegTokens calls authen.v1.AdminService.ListRegTokens.
func (c *adminServiceClient) ListRegTokens(ctx context.Context, req *connect.Request[v1.ListRegTokensRequest]) (*connect.Response[v1.RegTokenList], error) {
	return c.listRegTokens.CallUnary(ctx, req)
}

// RevokeRegToken calls authen.v1.AdminService.RevokeRegToken.
func (c *adminServiceClient) RevokeRegToken(ctx context.Context, req *connect.Request[v1.RevokeRegTokenRequest]) (*connect.Response[v1.RevokeRegTokenResponse], error) {
	return c.revokeRegToken.CallUnary(ctx, req)
}

// ApproveIdentity calls authen.v1.AdminService.ApproveIdentity.
func (c *adminServiceClient) ApproveIdentity(ctx context.Context, req *connect.Request[v1.ApproveIdentityRequest]) (*connect.Response[v1.ApproveIdentityResponse], error) {
	return c.approveIdentity.CallUnary(ctx, req)
}

// RejectIdentity calls authen.v1.AdminService.RejectIdentity.
func (c *adminServiceClient) RejectIdentity(ctx context.Context, req *connect.Request[v1.RejectIdentityRequest]) (*connect.Response[v1.RejectIdentityResponse], error) {
	return c.rejectIdentity.CallUnary(ctx, req)
}

// ListKeys calls authen.v1.AdminService.ListKeys.
func (c *adminServiceClient) ListKeys(ctx context.Context, req *connect.Request[v1.ListKeysRequest]) (*connect.Response[v1.KeyList], error) {
	return c.listKeys.CallUnary(ctx, req)
}

// DeleteKey calls authen.v1.AdminService.DeleteKey.
func (c *adminServiceClient) DeleteKey(ctx context.Context, req *connect.Request[v1.DeleteKeyRequest]) (*connect.Response[v1.DeleteKeyResponse], error) {
	return c.deleteKey.CallUnary(ctx, req)
}

// ApplyPolicy calls authen.v1.AdminService.ApplyPolicy.
func (c *adminServiceClient) ApplyPolicy(ctx context.Context, req *connect.Request[v1.ApplyPolicyRequest]) (*connect.Response[v1.ApplyPolicyResponse], error) {
	return c.applyPolicy.CallUnary(ctx, req)
}

// ListPolicies calls authen.v1.AdminService.ListPolicies.
func (c *adminServiceClient) ListPolicies(ctx context.Context, req *connect.Request[v1.ListPoliciesRequest]) (*connect.Response[v1.PolicyList], error) {
	return c.listPolicies.CallUnary(ctx, req)
}

// CheckPolicy calls authen.v1.AdminService.CheckPolicy.
func (c *adminServiceClient) CheckPolicy(ctx context.Context, req *connect.Request[v1.CheckPolicyRequest]) (*connect.Response[v1.CheckPolicyResponse], error) {
	return c.checkPolicy.CallUnary(ctx, req)
}

// GetServerInfo calls authen.v1.AdminService.GetServerInfo.
func (c *adminServiceClient) GetServerInfo(ctx context.Context, req *connect.Request[v1.GetServerInfoRequest]) (*connect.Response[v1.ServerInfo], error) {
	return c.getServerInfo.CallUnary(ctx, req)
}

// ListSessions calls authen.v1.AdminService.ListSessions.
func (c *adminServiceClient) ListSessions(ctx context.Context, req *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.SessionList], error) {
	return c.listSessions.CallUnary(ctx, req)
}

// RevokeSession calls authen.v1.AdminService.RevokeSession.
func (c *adminServiceClient) RevokeSession(ctx context.Context, req *connect.Request[v1.RevokeSessionRequest]) (*connect.Response[v1.RevokeSessionResponse], error) {
	return c.revokeSession.CallUnary(ctx, req)
}

// IssuePassport calls authen.v1.AdminService.IssuePassport.
func (c *adminServiceClient) IssuePassport(ctx context.Context, req *connect.Request[v1.IssuePassportRequest]) (*connect.Response[v1.IssuePassportResponse], error) {
	return c.issuePassport.CallUnary(ctx, req)
}

// AdminServiceHandler is an implementation of the authen.v1.AdminService service.
type AdminServiceHandler interface {
	IssueRegToken(context.Context, *connect.Request[v1.IssueRegTokenRequest]) (*connect.Response[v1.RegToken], error)
	ListRegTokens(context.Context, *connect.Request[v1.ListRegTokensRequest]) (*connect.Response[v1.RegTokenList], error)
	RevokeRegToken(context.Context, *connect.Request[v1.RevokeRegTokenRequest]) (*connect.Response[v1.RevokeRegTokenResponse], error)
	ApproveIdentity(context.Context, *connect.Request[v1.ApproveIdentityRequest]) (*connect.Response[v1.ApproveIdentityResponse], error)
	RejectIdentity(context.Context, *connect.Request[v1.RejectIdentityRequest]) (*connect.Response[v1.RejectIdentityResponse], error)
	ListKeys(context.Context, *connect.Request[v1.ListKeysRequest]) (*connect.Response[v1.KeyList], error)
	DeleteKey(context.Context, *connect.Request[v1.DeleteKeyRequest]) (*connect.Response[v1.DeleteKeyResponse], error)
	ApplyPolicy(context.Context, *connect.Request[v1.ApplyPolicyRequest]) (*connect.Response[v1.ApplyPolicyResponse], error)
	ListPolicies(context.Context, *connect.Request[v1.ListPoliciesRequest]) (*connect.Response[v1.PolicyList], error)
	CheckPolicy(context.Context, *connect.Request[v1.CheckPolicyRequest]) (*connect.Response[v1.CheckPolicyResponse], error)
	GetServerInfo(context.Context, *connect.Request[v1.GetServerInfoRequest]) (*connect.Response[v1.ServerInfo], error)
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.SessionList], error)
	RevokeSession(context.Context, *connect.Request[v1.RevokeSessionRequest]) (*connect.Response[v1.RevokeSessionResponse], error)
	IssuePassport(context.Context, *connect.Request[v1.IssuePassportRequest]) (*connect.Response[v1.IssuePassportResponse], error)
}

// NewAdminServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminServiceHandler(svc AdminServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminServiceMethods := v1.File_authen_v1_admin_proto.Services().ByName("AdminService").Methods()
	adminServiceIssueRegTokenHandler := connect.NewUnaryHandler(
		AdminServiceIssueRegTokenProcedure,
		svc.IssueRegToken,
		connect.WithSchema(adminServiceMethods.ByName("IssueRegToken")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListRegTokensHandler := connect.NewUnaryHandler(
		AdminServiceListRegTokensProcedure,
		svc.ListRegTokens,
		connect.WithSchema(adminServiceMethods.ByName("ListRegTokens")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceRevokeRegTokenHandler := connect.NewUnaryHandler(
		AdminServiceRevokeRegTokenProcedure,
		svc.RevokeRegToken,
		connect.WithSchema(adminServiceMethods.ByName("RevokeRegToken")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceApproveIdentityHandler := connect.NewUnaryHandler(
		AdminServiceApproveIdentityProcedure,
		svc.ApproveIdentity,
		connect.WithSchema(adminServiceMethods.ByName("ApproveIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceRejectIdentityHandler := connect.NewUnaryHandler(
		AdminServiceRejectIdentityProcedure,
		svc.RejectIdentity,
		connect.WithSchema(adminServiceMethods.ByName("RejectIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListKeysHandler := connect.NewUnaryHandler(
		AdminServiceListKeysProcedure,
		svc.ListKeys,
		connect.WithSchema(adminServiceMethods.ByName("ListKeys")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceDeleteKeyHandler := connect.NewUnaryHandler(
		AdminServiceDeleteKeyProcedure,
		svc.DeleteKey,
		connect.WithSchema(adminServiceMethods.ByName("DeleteKey")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceApplyPolicyHandler := connect.NewUnaryHandler(
		AdminServiceApplyPolicyProcedure,
		svc.ApplyPolicy,
		connect.WithSchema(adminServiceMethods.ByName("ApplyPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListPoliciesHandler := connect.NewUnaryHandler(
		AdminServiceListPoliciesProcedure,
		svc.ListPolicies,
		connect.WithSchema(adminServiceMethods.ByName("ListPolicies")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceCheckPolicyHandler := connect.NewUnaryHandler(
		AdminServiceCheckPolicyProcedure,
		svc.CheckPolicy,
		connect.WithSchema(adminServiceMethods.ByName("CheckPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceGetServerInfoHandler := connect.NewUnaryHandler(
		AdminServiceGetServerInfoProcedure,
		svc.GetServerInfo,
		connect.WithSchema(adminServiceMethods.ByName("GetServerInfo")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListSessionsHandler := connect.NewUnaryHandler(
		AdminServiceListSessionsProcedure,
		svc.ListSessions,
		connect.WithSchema(adminServiceMethods.ByName("ListSessions")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceRevokeSessionHandler := connect.NewUnaryHandler(
		AdminServiceRevokeSessionProcedure,
		svc.RevokeSession,
		connect.WithSchema(adminServiceMethods.ByName("RevokeSession")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceIssuePassportHandler := connect.NewUnaryHandler(
		AdminServiceIssuePassportProcedure,
		svc.IssuePassport,
		connect.WithSchema(adminServiceMethods.ByName("IssuePassport")),
		connect.WithHandlerOptions(opts...),
	)
	return "/authen.v1.AdminService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminServiceIssueRegTokenProcedure:
			adminServiceIssueRegTokenHandler.ServeHTTP(w, r)
		case AdminServiceListRegTokensProcedure:
			adminServiceListRegTokensHandler.ServeHTTP(w, r)
		case AdminServiceRevokeRegTokenProcedure:
			adminServiceRevokeRegTokenHandler.ServeHTTP(w, r)
		case AdminServiceApproveIdentityProcedure:
			adminServiceApproveIdentityHandler.ServeHTTP(w, r)
		case AdminServiceRejectIdentityProcedure:
			adminServiceRejectIdentityHandler.ServeHTTP(w, r)
		case AdminServiceListKeysProcedure:
			adminServiceListKeysHandler.ServeHTTP(w, r)
		case AdminServiceDeleteKeyProcedure:
			adminServiceDeleteKeyHandler.ServeHTTP(w, r)
		case AdminServiceApplyPolicyProcedure:
			adminServiceApplyPolicyHandler.ServeHTTP(w, r)
		case AdminServiceListPoliciesProcedure:
			adminServiceListPoliciesHandler.ServeHTTP(w, r)
		case AdminServiceCheckPolicyProcedure:
			adminServiceCheckPolicyHandler.ServeHTTP(w, r)
		case AdminServiceGetServerInfoProcedure:
			adminServiceGetServerInfoHandler.ServeHTTP(w, r)
		case AdminServiceListSessionsProcedure:
			adminServiceListSessionsHandler.ServeHTTP(w, r)
		case AdminServiceRevokeSessionProcedure:
			adminServiceRevokeSessionHandler.ServeHTTP(w, r)
		case AdminServiceIssuePassportProcedure:
			adminServiceIssuePassportHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminServiceHandler struct{}

func (UnimplementedAdminServiceHandler) IssueRegToken(context.Context, *connect.Request[v1.IssueRegTokenRequest]) (*connect.Response[v1.RegToken], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("authen.v1.AdminService.IssueRegToken is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListRegTokens(context.Context, *connect.Request[v1.ListRegTokensRequest]) (*connect.Response[v1.RegTokenList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("authen.v1.AdminService.ListRegTokens is not implemented"))
}

func (UnimplementedAdminServiceHandler) RevokeRegToken(context.Context, *connect.Request[v1.RevokeRegTokenRequest]) (*connect.Response[v1.RevokeRegTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("authen.v1.AdminService.RevokeRegToken is not implemented"))
}

func (UnimplementedAdminServiceHandler) ApproveIdentity(context.Context, *connect.Request[v1.ApproveIdentityRequest]) (*connect.Response[v1.ApproveIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("authen.v1.AdminService.ApproveIdentity is not implemented"))
}

func (UnimplementedAdminServiceHandler) RejectIdentity(context.Context, *connect.Request[v1.RejectIdentityRequest]) (*connect.Response[v1.RejectIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("authen.v1.AdminService.RejectIdentity is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListKeys(context.Context, *connect.Request[v1.ListKeysRequest]) (*connect.Response[v1.KeyList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("authen.v1.AdminService.ListKeys is not implemented"))
}

func (UnimplementedAdminServiceHandler) DeleteKey(context.Context, *connect.Request[v1.DeleteKeyRequest]) (*connect.Response[v1.DeleteKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("authen.v1.AdminService.DeleteKey is not implemented"))
}

func (UnimplementedAdminServiceHandler) ApplyPolicy(context.Context, *connect.Request[v1.ApplyPolicyRequest]) (*connect.Response[v1.ApplyPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("authen.v1.AdminService.ApplyPolicy is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListPolicies(context.Context, *connect.Request[v1.ListPoliciesRequest]) (*connect.Response[v1.PolicyList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("authen.v1.AdminService.ListPolicies is not implemented"))
}

func (UnimplementedAdminServiceHandler) CheckPolicy(context.Context, *connect.Request[v1.CheckPolicyRequest]) (*connect.Response[v1.CheckPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("authen.v1.AdminService.CheckPolicy is not implemented"))
}

func (UnimplementedAdminServiceHandler) GetServerInfo(context.Context, *connect.Request[v1.GetServerInfoRequest]) (*connect.Response[v1.ServerInfo], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("authen.v1.AdminService.GetServerInfo is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.SessionList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("authen.v1.AdminService.ListSessions is not implemented"))
}

func (UnimplementedAdminServiceHandler) RevokeSession(context.Context, *connect.Request[v1.RevokeSessionRequest]) (*connect.Response[v1.RevokeSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("authen.v1.AdminService.RevokeSession is not implemented"))
}

func (UnimplementedAdminServiceHandler) IssuePassport(context.Context, *connect.Request[v1.IssuePassportRequest]) (*connect.Response[v1.IssuePassportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("authen.v1.AdminService.IssuePassport is not implemented"))
}
