// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: authen/v1/auth.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/jonathan-chery/authen-proto/pkg/proto/authen/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "authen.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceRegisterProcedure is the fully-qualified name of the AuthService's Register RPC.
	AuthServiceRegisterProcedure = "/authen.v1.AuthService/Register"
	// AuthServiceChallengeProcedure is the fully-qualified name of the AuthService's Challenge RPC.
	AuthServiceChallengeProcedure = "/authen.v1.AuthService/Challenge"
	// AuthServiceVerifyProcedure is the fully-qualified name of the AuthService's Verify RPC.
	AuthServiceVerifyProcedure = "/authen.v1.AuthService/Verify"
	// AuthServiceRefreshProcedure is the fully-qualified name of the AuthService's Refresh RPC.
	AuthServiceRefreshProcedure = "/authen.v1.AuthService/Refresh"
	// AuthServiceRevokeProcedure is the fully-qualified name of the AuthService's Revoke RPC.
	AuthServiceRevokeProcedure = "/authen.v1.AuthService/Revoke"
	// AuthServiceValidateProcedure is the fully-qualified name of the AuthService's Validate RPC.
	AuthServiceValidateProcedure = "/authen.v1.AuthService/Validate"
	// AuthServiceRotateKeyProcedure is the fully-qualified name of the AuthService's RotateKey RPC.
	AuthServiceRotateKeyProcedure = "/authen.v1.AuthService/RotateKey"
	// AuthServiceVerifyPassportProcedure is the fully-qualified name of the AuthService's
	// VerifyPassport RPC.
	AuthServiceVerifyPassportProcedure = "/authen.v1.AuthService/VerifyPassport"
)

// AuthServiceClient is a client for the authen.v1.AuthService service.
type AuthServiceClient interface {
	Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error)
	Challenge(context.Context, *connect.Request[v1.ChallengeRequest]) (*connect.Response[v1.ChallengeResponse], error)
	Verify(context.Context, *connect.Request[v1.VerifyRequest]) (*connect.Response[v1.TokenPair], error)
	Refresh(context.Context, *connect.Request[v1.RefreshRequest]) (*connect.Response[v1.TokenPair], error)
	Revoke(context.Context, *connect.Request[v1.RevokeRequest]) (*connect.Response[v1.RevokeResponse], error)
	Validate(context.Context, *connect.Request[v1.ValidateRequest]) (*connect.Response[v1.ValidateResponse], error)
	RotateKey(context.Context, *connect.Request[v1.RotateKeyRequest]) (*connect.Response[v1.RotateKeyResponse], error)
	VerifyPassport(context.Context, *connect.Request[v1.VerifyPassportRequest]) (*connect.Response[v1.VerifyPassportResponse], error)
}

// NewAuthServiceClient constructs a client for the authen.v1.AuthService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := v1.File_authen_v1_auth_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		register: connect.NewClient[v1.RegisterRequest, v1.RegisterResponse](
			httpClient,
			baseURL+AuthServiceRegisterProcedure,
			connect.WithSchema(authServiceMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
		challenge: connect.NewClient[v1.ChallengeRequest, v1.ChallengeResponse](
			httpClient,
			baseURL+AuthServiceChallengeProcedure,
			connect.WithSchema(authServiceMethods.ByName("Challenge")),
			connect.WithClientOptions(opts...),
		),
		verify: connect.NewClient[v1.VerifyRequest, v1.TokenPair](
			httpClient,
			baseURL+AuthServiceVerifyProcedure,
			connect.WithSchema(authServiceMethods.ByName("Verify")),
			connect.WithClientOptions(opts...),
		),
		refresh: connect.NewClient[v1.RefreshRequest, v1.TokenPair](
			httpClient,
			baseURL+AuthServiceRefreshProcedure,
			connect.WithSchema(authServiceMethods.ByName("Refresh")),
			connect.WithClientOptions(opts...),
		),
		revoke: connect.NewClient[v1.RevokeRequest, v1.RevokeResponse](
			httpClient,
			baseURL+AuthServiceRevokeProcedure,
			connect.WithSchema(authServiceMethods.ByName("Revoke")),
			connect.WithClientOptions(opts...),
		),
		validate: connect.NewClient[v1.ValidateRequest, v1.ValidateResponse](
			httpClient,
			baseURL+AuthServiceValidateProcedure,
			connect.WithSchema(authServiceMethods.ByName("Validate")),
			connect.WithClientOptions(opts...),
		),
		rotateKey: connect.NewClient[v1.RotateKeyRequest, v1.RotateKeyResponse](
			httpClient,
			baseURL+AuthServiceRotateKeyProcedure,
			connect.WithSchema(authServiceMethods.ByName("RotateKey")),
			connect.WithClientOptions(opts...),
		),
		verifyPassport: connect.NewClient[v1.VerifyPassportRequest, v1.VerifyPassportResponse](
			httpClient,
			baseURL+AuthServiceVerifyPassportProcedure,
			connect.WithSchema(authServiceMethods.ByName("VerifyPassport")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	register       *connect.Client[v1.RegisterRequest, v1.RegisterResponse]
	challenge      *connect.Client[v1.ChallengeRequest, v1.ChallengeResponse]
	verify         *connect.Client[v1.VerifyRequest, v1.TokenPair]
	refresh        *connect.Client[v1.RefreshRequest, v1.TokenPair]
	revoke         *connect.Client[v1.RevokeRequest, v1.RevokeResponse]
	validate       *connect.Client[v1.ValidateRequest, v1.ValidateResponse]
	rotateKey      *connect.Client[v1.RotateKeyRequest, v1.RotateKeyResponse]
	verifyPassport *connect.Client[v1.VerifyPassportRequest, v1.VerifyPassportResponse]
}

// Register calls authen.v1.AuthService.Register.
func (c *authServiceClient) Register(ctx context.Context, req *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error) {
	return c.register.CallUnary(ctx, req)
}

// Challenge calls authen.v1.AuthService.Challenge.
func (c *authServiceClient) Challenge(ctx context.Context, req *connect.Request[v1.ChallengeRequest]) (*connect.Response[v1.ChallengeResponse], error) {
	return c.challenge.CallUnary(ctx, req)
}

// Verify calls authen.v1.AuthService.Verify.
func (c *authServiceClient) Verify(ctx context.Context, req *connect.Request[v1.VerifyRequest]) (*connect.Response[v1.TokenPair], error) {
	return c.verify.CallUnary(ctx, req)
}

// Refresh calls authen.v1.AuthService.Refresh.
func (c *authServiceClient) Refresh(ctx context.Context, req *connect.Request[v1.RefreshRequest]) (*connect.Response[v1.TokenPair], error) {
	return c.refresh.CallUnary(ctx, req)
}

// Revoke calls authen.v1.AuthService.Revoke.
func (c *authServiceClient) Revoke(ctx context.Context, req *connect.Request[v1.RevokeRequest]) (*connect.Response[v1.RevokeResponse], error) {
	return c.revoke.CallUnary(ctx, req)
}

// Validate calls authen.v1.AuthService.Validate.
func (c *authServiceClient) Validate(ctx context.Context, req *connect.Request[v1.ValidateRequest]) (*connect.Response[v1.ValidateResponse], error) {
	return c.validate.CallUnary(ctx, req)
}

// RotateKey calls authen.v1.AuthService.RotateKey.
func (c *authServiceClient) RotateKey(ctx context.Context, req *connect.Request[v1.RotateKeyRequest]) (*connect.Response[v1.RotateKeyResponse], error) {
	return c.rotateKey.CallUnary(ctx, req)
}

// VerifyPassport calls authen.v1.AuthService.VerifyPassport.
func (c *authServiceClient) VerifyPassport(ctx context.Context, req *connect.Request[v1.VerifyPassportRequest]) (*connect.Response[v1.VerifyPassportResponse], error) {
	return c.verifyPassport.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the authen.v1.AuthService service.
type AuthServiceHandler interface {
	Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error)
	Challenge(context.Context, *connect.Request[v1.ChallengeRequest]) (*connect.Response[v1.ChallengeResponse], error)
	Verify(context.Context, *connect.Request[v1.VerifyRequest]) (*connect.Response[v1.TokenPair], error)
	Refresh(context.Context, *connect.Request[v1.RefreshRequest]) (*connect.Response[v1.TokenPair], error)
	Revoke(context.Context, *connect.Request[v1.RevokeRequest]) (*connect.Response[v1.RevokeResponse], error)
	Validate(context.Context, *connect.Request[v1.ValidateRequest]) (*connect.Response[v1.ValidateResponse], error)
	RotateKey(context.Context, *connect.Request[v1.RotateKeyRequest]) (*connect.Response[v1.RotateKeyResponse], error)
	VerifyPassport(context.Context, *connect.Request[v1.VerifyPassportRequest]) (*connect.Response[v1.VerifyPassportResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := v1.File_authen_v1_auth_proto.Services().ByName("AuthService").Methods()
	authServiceRegisterHandler := connect.NewUnaryHandler(
		AuthServiceRegisterProcedure,
		svc.Register,
		connect.WithSchema(authServiceMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceChallengeHandler := connect.NewUnaryHandler(
		AuthServiceChallengeProcedure,
		svc.Challenge,
		connect.WithSchema(authServiceMethods.ByName("Challenge")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceVerifyHandler := connect.NewUnaryHandler(
		AuthServiceVerifyProcedure,
		svc.Verify,
		connect.WithSchema(authServiceMethods.ByName("Verify")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRefreshHandler := connect.NewUnaryHandler(
		AuthServiceRefreshProcedure,
		svc.Refresh,
		connect.WithSchema(authServiceMethods.ByName("Refresh")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRevokeHandler := connect.NewUnaryHandler(
		AuthServiceRevokeProcedure,
		svc.Revoke,
		connect.WithSchema(authServiceMethods.ByName("Revoke")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceValidateHandler := connect.NewUnaryHandler(
		AuthServiceValidateProcedure,
		svc.Validate,
		connect.WithSchema(authServiceMethods.ByName("Validate")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRotateKeyHandler := connect.NewUnaryHandler(
		AuthServiceRotateKeyProcedure,
		svc.RotateKey,
		connect.WithSchema(authServiceMethods.ByName("RotateKey")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceVerifyPassportHandler := connect.NewUnaryHandler(
		AuthServiceVerifyPassportProcedure,
		svc.VerifyPassport,
		connect.WithSchema(authServiceMethods.ByName("VerifyPassport")),
		connect.WithHandlerOptions(opts...),
	)
	return "/authen.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceRegisterProcedure:
			authServiceRegisterHandler.ServeHTTP(w, r)
		case AuthServiceChallengeProcedure:
			authServiceChallengeHandler.ServeHTTP(w, r)
		case AuthServiceVerifyProcedure:
			authServiceVerifyHandler.ServeHTTP(w, r)
		case AuthServiceRefreshProcedure:
			authServiceRefreshHandler.ServeHTTP(w, r)
		case AuthServiceRevokeProcedure:
			authServiceRevokeHandler.ServeHTTP(w, r)
		case AuthServiceValidateProcedure:
			authServiceValidateHandler.ServeHTTP(w, r)
		case AuthServiceRotateKeyProcedure:
			authServiceRotateKeyHandler.ServeHTTP(w, r)
		case AuthServiceVerifyPassportProcedure:
			authServiceVerifyPassportHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("authen.v1.AuthService.Register is not implemented"))
}

func (UnimplementedAuthServiceHandler) Challenge(context.Context, *connect.Request[v1.ChallengeRequest]) (*connect.Response[v1.ChallengeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("authen.v1.AuthService.Challenge is not implemented"))
}

func (UnimplementedAuthServiceHandler) Verify(context.Context, *connect.Request[v1.VerifyRequest]) (*connect.Response[v1.TokenPair], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("authen.v1.AuthService.Verify is not implemented"))
}

func (UnimplementedAuthServiceHandler) Refresh(context.Context, *connect.Request[v1.RefreshRequest]) (*connect.Response[v1.TokenPair], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("authen.v1.AuthService.Refresh is not implemented"))
}

func (UnimplementedAuthServiceHandler) Revoke(context.Context, *connect.Request[v1.RevokeRequest]) (*connect.Response[v1.RevokeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("authen.v1.AuthService.Revoke is not implemented"))
}

func (UnimplementedAuthServiceHandler) Validate(context.Context, *connect.Request[v1.ValidateRequest]) (*connect.Response[v1.ValidateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("authen.v1.AuthService.Validate is not implemented"))
}

func (UnimplementedAuthServiceHandler) RotateKey(context.Context, *connect.Request[v1.RotateKeyRequest]) (*connect.Response[v1.RotateKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("authen.v1.AuthService.RotateKey is not implemented"))
}

func (UnimplementedAuthServiceHandler) VerifyPassport(context.Context, *connect.Request[v1.VerifyPassportRequest]) (*connect.Response[v1.VerifyPassportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("authen.v1.AuthService.VerifyPassport is not implemented"))
}
